### ISSUE TITLE
minimal image

### ISSUE THREAD

**Issue by missinglink** [pelias/docker-baseimage#21]
It might be worth trying to strip this image down to only `runtime` dependencies.

Most of our code requires only `node` and `npm` (couple other things?) to function, so it would benefit from a minimal `runtime` image which didn't include >100MB of compilers and other programming languages etc.

For the other repos which require build utils or things like `jq` we could start doing something more like https://github.com/pelias/spatial/blob/master/Dockerfile where we build what is required on a per-image basis.

It's not a huge deal but our current `pelias/baseimage` is `516MB` so obviously anything we build on top of it is going to be larger than that.

> for instance I spent a bunch of time on `pelias/spatial` which has lots of dependencies and could only get it down to `709MB`

Looking inside it's easy to see some quick wins at the expense of convenience:

```bash
docker run --rm --entrypoint=bash -it pelias/baseimage:latest -c 'du -sh /usr'
473M	/usr
```

```bash
docker run --rm --entrypoint=bash -it pelias/baseimage:latest -c 'du -sh /usr/*'
45M	/usr/bin
...
21M	/usr/include
264M	/usr/lib
86M	/usr/local
...
```

```
docker run --rm --entrypoint=bash -it pelias/baseimage:latest -c 'du -sh /usr/lib/*'
...
89M	/usr/lib/gcc
22M	/usr/lib/git-core
...
3.3M	/usr/lib/locale
...
122M	/usr/lib/x86_64-linux-gnu
```

```bash
docker run --rm --entrypoint=bash -it pelias/baseimage:latest -c 'du -sh /usr/lib/x86_64-linux-gnu/*' | grep M
6.5M	/usr/lib/x86_64-linux-gnu/gconv
...
5.3M	/usr/lib/x86_64-linux-gnu/libc.a
...
26M	/usr/lib/x86_64-linux-gnu/libicudata.so.60.2
...
20M	/usr/lib/x86_64-linux-gnu/perl
4.9M	/usr/lib/x86_64-linux-gnu/perl-base
```

**Comment by orangejulius** [comment]
Yeah, a lot of this size is due to including compliers so we can build `better-sqlite3`. However, since they recently started shipping precompiled binaries, that probably isn't needed anymore.

Even if it _is_ required, we could use multistage builds to keep the complier tools out of the final baseimage.

Personally, I like having a reasonably full set of linux utils in our baseimages, but ubuntu itself is only ~60MB, so we can probably keep it.

**Comment by missinglink** [comment]
In that case we might want to create a new tag `pelias/baseimage:runtime` which is minimal and leave `pelias/baseimage:latest` as the full set of utils so we can pick and choose on a case-by-case basis?
